/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:140c6bd5-1a1b-4852-b1a6-aacf0529f94f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_V8g48edSV",
    "aws_user_pools_web_client_id": "6hpcmbbkf8a3h9f2gp5gej7odo",
    "oauth": {}
};


export default awsmobile;
